const JSON_DATA_URL = 'json-data'

const PROJECTS_DATA_ENDPOINT = `${JSON_DATA_URL}/projectsList.json`
const ABOUT_US_DATA_ENDPOINT = `${JSON_DATA_URL}/aboutUsData.json`
const CONTACTS_DATA_ENDPOINT = `${JSON_DATA_URL}/contactsData.json`
const PLACES_DATA_ENDPOINT = `${JSON_DATA_URL}/placesList.json`
const PROPOSAL_DATA_ENDPOINT = `${JSON_DATA_URL}/proposalList.json`
const REQUISITES_DATA_ENDPOINT = `${JSON_DATA_URL}/requisites.json`
const TEAM_DATA_ENDPOINT = `${JSON_DATA_URL}/team.json`
const CONTACT_FORM_ENDPOINT = '/contact.php'

export {
    PROJECTS_DATA_ENDPOINT,
    ABOUT_US_DATA_ENDPOINT,
    CONTACTS_DATA_ENDPOINT,
    PLACES_DATA_ENDPOINT,
    PROPOSAL_DATA_ENDPOINT,
    REQUISITES_DATA_ENDPOINT,
    TEAM_DATA_ENDPOINT,
    CONTACT_FORM_ENDPOINT,
}
